################################################################################
### a collection of docs for APCD data-organization
### version controlled by git
################################################################################

## columns selected for medical claim value sets.
mc.col.out <- c(
  "medical_claim_service_line_id",
  "submitter_id",                
  "product_code",
  "internal_member_id",          
  "first_service_dt",
  "last_service_dt",              
  "admission_dt",
  "discharge_dt",                 
  "place_of_service_code",
  "type_of_bill_code",            
  "type_of_setting_id",
  "quantity",                     
  "charge_amt",  
  "paid_amt" ,                    
 "copay_amt",
 "coinsurance_amt",              
 "deductible_amt",
 "prepaid_amt",
"claim_status_code",
 "procedure_code",
    "procedure_modifier_code_1",
"procedure_modifier_code_2",
   "procedure_modifier_code_3",
"procedure_modifier_code_4",    
  "revenue_code",
"diagnosis_code",               
 "icd_procedure_code",
"discharge_status_code",
 "orphaned_adjustment_flag",
"denied_claim_flag",           
  "medical_claim_header_id",
"rendering_provider_id",        
 "billing_provider_id",
"icd_version",
    NULL
)

## columns selected for pharmacy claim value sets.
pc.col.out <- c(
    'pharmacy_claim_service_line_id',
    'LINE_COUNTER',
    'INTERNAL_MEMBER_ID',
    'prescription_filled_dt',
    'NATIONAL_DRUG_CODE',
    'DRUG_NAME',
    'REFILL_NUMBER',
    'QUANTITY',
    'DAYS_SUPPLY',
    'THIRTY_DAY_EQUIVALENT',
    'CLAIM_STATUS_CODE', 
    'DENIED_CLAIM_FLAG',
    'PHARMACY_PROVIDER_ID',
    'PRSCRBING_PROVIDER_ID', 
    NULL
)

### Taxo detail information matrix

taxo_info <- rbind(data.table('taxo' = '207Q00000X', 'spec1' = 'FP', 'reference' = 'CMS08',
                              'description' = 'Allopathic & Osteopathic Physicians/Family Medicine'),
                   data.table('taxo' = '207QA0000X', 'spec1' = 'FP', 'reference' = 'CMS08',
                              'description' = 'Allopathic & Osteopathic Physicians/Family Medicine, Adolescent Medicine'),
                   data.table('taxo' = '207QA0505X', 'spec1' = 'FP', 'reference' = 'CMS08',
                              'description' = 'Allopathic & Osteopathic Physicians/Family Medicine, Adult Medicine'),
                   data.table('taxo' = '207QG0300X', 'spec1' = 'FP', 'reference' = 'CMS08',
                              'description' = 'Allopathic & Osteopathic Physicians/Family Medicine, Geriatric Medicine'),
                   data.table('taxo' = '208D00000X', 'spec1' = 'GP', 'reference' = 'CMS01',
                              'description' = 'Allopathic & Osteopathic Physicians/General Practice'),
                   data.table('taxo' = '207R00000X', 'spec1' = 'IM', 'reference' = 'CMS11',
                              'description' = 'Allopathic & Osteopathic Physicians/Internal Medicine'),
                   data.table('taxo' = '207RA0000X', 'spec1' = 'IM', 'reference' = 'CMS11',
                              'description' = 'Allopathic & Osteopathic Physicians/Internal Medicine, Adolescent Medicine'),
                   data.table('taxo' = '207RG0300X', 'spec1' = 'IM', 'reference' = 'CMS11',
                              'description' = 'Allopathic & Osteopathic Physicians/Internal Medicine, Geriatric Medicine'),
                   data.table('taxo' = '208000000X', 'spec1' = 'PedM', 'reference' = 'CMS37',
                              'description' = 'Allopathic & Osteopathic Physicians/Pediatrics'),
                   data.table('taxo' = '2080A0000X', 'spec1' = 'PedM', 'reference' = 'CMS37',
                              'description' = 'Allopathic & Osteopathic Physicians/Pediatrics, Adolescent Medicine'),
                   data.table('taxo' = '363L00000X', 'spec1' = 'NP', 'reference' = 'CMS50',
                              'description' = 'Physician Assistants & Advanced Practice Nursing Providers/Nurse Practitioner'),
                   data.table('taxo' = '363LA2200X', 'spec1' = 'NP', 'reference' = 'CMS50',
                              'description' = 'Physician Assistants & Advanced Practice Nursing Providers/Nurse Practitioner, Adult Health'),
                   data.table('taxo' = '363LC1500X', 'spec1' = 'NP', 'reference' = 'CMS50',
                              'description' = 'Physician Assistants & Advanced Practice Nursing Providers/Nurse Practitioner, Community Health'),
                   data.table('taxo' = '363LF0000X', 'spec1' = 'NP', 'reference' = 'CMS50',
                              'description' = 'Physician Assistants & Advanced Practice Nursing Providers/Nurse Practitioner, Family'),
                   data.table('taxo' = '363LG0600X', 'spec1' = 'NP', 'reference' = 'CMS50',
                              'description' = 'Physician Assistants & Advanced Practice Nursing Providers/Nurse Practitioner, Gerontology'),
                   data.table('taxo' = '363LP0200X', 'spec1' = 'NP', 'reference' = 'CMS50',
                              'description' = 'Physician Assistants & Advanced Practice Nursing Providers/Nurse Practitioner, Pediatrics'),
                   data.table('taxo' = '363LP2300X', 'spec1' = 'NP', 'reference' = 'CMS50',
                              'description' = 'Physician Assistants & Advanced Practice Nursing Providers/Nurse Practitioner, Primary Care'),
                   data.table('taxo' = '364S00000X', 'spec1' = 'CCNS', 'reference' = 'CMS89',
                              'description' = 'Physician Assistants & Advanced Practice Nursing Providers/Clinical Nurse Specialist'),
                   data.table('taxo' = '364SA2200X', 'spec1' = 'CCNS', 'reference' = 'CMS89',
                              'description' = 'Physician Assistants & Advanced Practice Nursing Providers/Clinical Nurse Specialist, Adult Health'),
                   data.table('taxo' = '364SC1501X', 'spec1' = 'CCNS', 'reference' = 'CMS89',
                              'description' = 'Physician Assistants & Advanced Practice Nursing Providers/Clinical Nurse Specialist, Community Health/Public Health'),
                   data.table('taxo' = '364SF0001X', 'spec1' = 'CCNS', 'reference' = 'CMS89',
                              'description' = 'Physician Assistants & Advanced Practice Nursing Providers/Clinical Nurse Specialist, Family Health'),
                   data.table('taxo' = '364SG0600X', 'spec1' = 'CCNS', 'reference' = 'CMS89',
                              'description' = 'Physician Assistants & Advanced Practice Nursing Providers/Clinical Nurse Specialist, Gerontology'),
                   data.table('taxo' = '364SP0200X', 'spec1' = 'CCNS', 'reference' = 'CMS89',
                              'description' = 'Physician Assistants & Advanced Practice Nursing Providers/Clinical Nurse Specialist, Pediatrics'),
                   data.table('taxo' = '363A00000X', 'spec1' = 'PA', 'reference' = 'CMS97',
                              'description' = 'Physician Assistants & Advanced Practice Nursing Providers/Physician Assistant'),
                   data.table('taxo' = '363AM0700X', 'spec1' = 'PA', 'reference' = 'CMS97',
                              'description' = 'Physician Assistants & Advanced Practice Nursing Providers/Physician Assistant, Medical'),
                   data.table('taxo' = '207V00000X', 'spec1' = 'OBGYN', 'reference' = 'CMS16',
                              'description' = 'Allopathic & Osteopathic Physicians/Obstetrics & Gynecology'),
                   data.table('taxo' = '207VG0400X', 'spec1' = 'OBGYN', 'reference' = 'CMS16',
                              'description' = 'Allopathic & Osteopathic Physicians/Obstetrics & Gynecology, Gynecology'),
                   data.table('taxo' = '207VX0000X', 'spec1' = 'OBGYN', 'reference' = 'CMS16',
                              'description' = 'Allopathic & Osteopathic Physicians/Obstetrics & Gynecology, Obstetrics'),
                   data.table('taxo' = '363LX0001X', 'spec1' = 'OBGYN', 'reference' = 'sup',
                              'description' = 'Physician Assistants & Advanced Practice Nursing Providers/Nurse Practitioner, Obstetrics & Gynecology'),
                   data.table('taxo' = '363LW0102X', 'spec1' = 'OBGYN', 'reference' = 'sup',
                              'description' = "Physician Assistants & Advanced Practice Nursing Providers/Nurse Practitioner, Women's Health"),
                   data.table('taxo' = '364SW0102X', 'spec1' = 'OBGYN', 'reference' = 'sup',
                              'description' = "Physician Assistants & Advanced Practice Nursing Providers/Clinical Nurse Specialist, Women's Health"),
                   NULL # placeholder for comments
)
taxo_info[spec1 %in% c('FP',
                       'GP',
                       'IM',
                       'PedM',
                       'NP',
                       'CCNS',
                       'PA'),
          spec0 := 'PCP'][spec1 %in% c('OBGYN'),
                          spec0 := 'OBGYN']
